version: "3.10"
services:
  worker:
    build: .
    environment:
      SESSION: $SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      API_TOKEN: $API_TOKEN 
